-- DCR tables for the GAME database (the one that holds teams, ledger,
-- sessions). NOT the DCR data database. Run once as the owner of the game
-- database. Safe to re-run.
--
-- The type of team_id is read from teams.id so the foreign key matches
-- whatever that column is (integer, bigint, uuid, ...).

DO $$
DECLARE
  team_type text := 'integer';
  fk        text := '';
BEGIN
  IF to_regclass('public.teams') IS NOT NULL THEN
    SELECT format_type(a.atttypid, a.atttypmod) INTO team_type
      FROM pg_attribute a
     WHERE a.attrelid = 'public.teams'::regclass AND a.attname = 'id' AND NOT a.attisdropped;
    fk := ' REFERENCES teams (id)';
  END IF;

  CREATE TABLE IF NOT EXISTS dcr_missions (
    id                   text PRIMARY KEY,                       -- 'M01' ... 'M15'
    level                integer NOT NULL CHECK (level BETWEEN 1 AND 4),
    title                text NOT NULL,
    story                text NOT NULL,
    question             text NOT NULL,
    answer_format        text NOT NULL,
    reward_cit           integer NOT NULL CHECK (reward_cit >= 0),
    reward_ce            integer NOT NULL CHECK (reward_ce >= 0),
    prerequisite         text REFERENCES dcr_missions (id),      -- M04 <- M03, M10 <- M09
    first_blood_eligible boolean NOT NULL DEFAULT false,         -- levels 2, 3, 4
    answer_hash          text NOT NULL,                          -- HMAC-SHA256, never the answer itself
    epilogue             text                                    -- only M15
  );

  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS dcr_solves (
      team_id     %s NOT NULL%s,
      mission_id  text NOT NULL REFERENCES dcr_missions (id),
      nickname    text NOT NULL,
      solved_at   timestamptz NOT NULL DEFAULT now(),
      first_blood boolean NOT NULL DEFAULT false,
      cit_paid    integer NOT NULL,
      ce_paid     integer NOT NULL,
      PRIMARY KEY (team_id, mission_id)                          -- paid once per team and mission
    )$f$, team_type, fk);

  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS dcr_attempts (
      attempt_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      team_id      %s NOT NULL%s,
      mission_id   text NOT NULL REFERENCES dcr_missions (id),
      nickname     text NOT NULL,
      correct      boolean NOT NULL,
      submitted_at timestamptz NOT NULL DEFAULT now()
    )$f$, team_type, fk);

  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS dcr_query_log (
      query_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      team_id    %s NOT NULL%s,
      nickname   text,
      sql_text   text NOT NULL,
      ok         boolean NOT NULL,
      ms         integer,
      created_at timestamptz NOT NULL DEFAULT now()
    )$f$, team_type, fk);
END $$;

CREATE INDEX IF NOT EXISTS dcr_attempts_recent_idx ON dcr_attempts (team_id, mission_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS dcr_solves_mission_idx  ON dcr_solves (mission_id, solved_at);
CREATE INDEX IF NOT EXISTS dcr_query_log_team_idx  ON dcr_query_log (team_id, created_at DESC);
